name = "Miit Create"
author = "Nick"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12fa69b2e3cb02059571cc534bc854935943117420eb777e6548dc71b7ff8771"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
